version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: zc1021
      MYSQL_DATABASE: job
      MYSQL_USER: cong
      MYSQL_PASSWORD: zc1021
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
    - "3306:3306"

    # TODO app